FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o hackatime

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/hackatime .

RUN mkdir -p /app/config

EXPOSE 3000

ENTRYPOINT ["./hackatime", "-config", "/app/config/config.yml"]
