FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o hackatime

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache curl

COPY --from=builder /app/hackatime .
COPY --from=builder /app/config.yml config.yml

EXPOSE 3000

ENTRYPOINT ["./hackatime", "-config", "config.yml"]
